name: Build Api Docs

on:
  push:
    branches:
      - "main"

jobs:
  build-api-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build References
        run: yarn run build:docs

      - name: Check for docs changes and commit if exists
        run: |
          if ! git diff --quiet docs; then
            echo "Changes detected in docs, committing..."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Auto-update docs"
            git push
          else
            echo "No changes in docs, skipping commit."
            exit 0
          fi
