name: Create Pull Request

on:
  push:
    branches-ignore:
      - 'main' # Exclude main branch

jobs:
  pr-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          base: 'main' # Base branch for PR
          title: 'New PR do not forget to change the title'
          draft: true 
