name: Run Benchmark

on:
  push:
    branches:
      - "does-not-exist"

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn run bench
